title: Go Programming
description: Free, evolving Go programming textbooks
theme: just-the-docs

plugins:
  - jekyll-sitemap

url: https://gorgo.dev
baseurl: /go

aux_links:
  GitHub:
    - https://github.com/BooksByGorgo/go

color_scheme: light

footer_content: >-
  Licensed under <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>.

nav_sort: case_insensitive

exclude:
  - Gemfile
  - Gemfile.lock
